In [2]:
import numpy as np
a = np.array([1,2,3,4,45])
print(a)

[ 1  2  3  4 45]


In [3]:
import time
toc = time.time()
a = np.random.rand(100000)
b = np.random.rand(100000)
tic = time.time()
print(np.dot(a,b),str(1000*(tic-toc)))

24932.6652838 4.999876022338867


In [4]:
c = 0 
tic = time.time()
for i in range(100000):
    c+=a[i]*b[i]
toc = time.time()
print(c, str(1000*(toc-tic)))

24932.6652838 82.0000171661377


In [7]:
A = np.array([[56,0,4.4,68],
            [1.2,104,52,8],
            [1.8,135,99,0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [15]:
# axis=0 代表纵向求和 axis=1代表横向求和
cal = A.sum(axis=0)
print(cal)
print(type(cal))
print(cal.reshape(1,4))  
print(type(cal.reshape(1,4)))

[  59.   239.   155.4   76.9]
<class 'numpy.ndarray'>
[[  59.   239.   155.4   76.9]]
<class 'numpy.ndarray'>


In [16]:
percentage = 100*A/cal.reshape(1,4) #这里使用reshape主要为了确定使用的是证券的列向量或行向量 以保证矩阵是我们想要的
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [17]:
x = np.random.rand(5)
print(x)

[ 0.50916395  0.08942183  0.26568978  0.86898965  0.91394954]


In [19]:
print(x.shape)

(5,)


In [20]:
print(x.T)

[ 0.50916395  0.08942183  0.26568978  0.86898965  0.91394954]


In [22]:
print(np.dot(x,x.T))

1.92828202442


In [23]:
a = np.random.rand(5,1)
print(a)

[[ 0.69047573]
 [ 0.08037782]
 [ 0.76586215]
 [ 0.0654184 ]
 [ 0.64721283]]


In [25]:
print(a.shape)

(5, 1)


In [26]:
print(a.T)

[[ 0.69047573  0.08037782  0.76586215  0.0654184   0.64721283]]


In [27]:
print(np.dot(a,a.T))

[[ 0.47675673  0.05549893  0.52880923  0.04516981  0.44688475]
 [ 0.05549893  0.00646059  0.06155833  0.00525819  0.05202155]
 [ 0.52880923  0.06155833  0.58654484  0.05010147  0.49567581]
 [ 0.04516981  0.00525819  0.05010147  0.00427957  0.04233962]
 [ 0.44688475  0.05202155  0.49567581  0.04233962  0.41888444]]


In [28]:
print(np.random.randn(5,1))

[[ 0.1726554 ]
 [-1.74107033]
 [ 1.23614573]
 [-0.59888848]
 [ 1.19346456]]


In [30]:
print(a.shape)

(5, 1)


In [32]:
assert(a.shape == (5,1))

In [33]:
print(a)

[[ 0.69047573]
 [ 0.08037782]
 [ 0.76586215]
 [ 0.0654184 ]
 [ 0.64721283]]


In [34]:
print(a.reshape((1,5)))

[[ 0.69047573  0.08037782  0.76586215  0.0654184   0.64721283]]
